/**
 * @author Prashant Bansod
 * @date 04-10-01
 * Javascript to handle switch course functionality
 */



/*********Ajax call for fetching centres for switch role starts***********/
/**
 * Function for making ajax call to retreive centre details
 */
function ajaxCoursesRetrieval()
{
	   try{
				// Opera 8.0+, Firefox, Safari
		    	xmlHttpRequest = new XMLHttpRequest();
			} catch (e)
			{
						// Internet Explorer Browsers
						try{
							xmlHttpRequest = new ActiveXObject("Msxml2.XMLHTTP");
						} catch (e) {
										try{
											xmlHttpRequest = new ActiveXObject("Microsoft.XMLHTTP");
										} catch (e){
											// Something went wrong
											alert("Please refresh or restart browser again");
											return false;
										}
									}
			}

    
		xmlHttpRequest.onreadystatechange=function ()
		{
			if(xmlHttpRequest.readyState==4 && xmlHttpRequest.status==200)
				responseHandler(xmlHttpRequest);
			
			else 
			{
				if(document.getElementById('divCourses')!=null)
					document.getElementById('divCourses').innerHTML="<div style=\"margin:100px;0px;0px;0px;\"><img src=\"images/ajaxLoader.gif\" style=\"width:40px;height:40px;\"></div>";
			}
		};
		params="";		//compulsory for calling servlet
		xmlHttpRequest.open("POST","FetchAvailableCourses",true);
		xmlHttpRequest.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
		xmlHttpRequest.setRequestHeader("Content-length", params.length);
		xmlHttpRequest.send(params);
		//xmlHttpRequest.setRequestHeader("Cache-Control","no-cache");
		//xmlHttpRequest.setRequestHeader("Pragma","no-cache");

		//xmlHttpRequest.setRequestHeader("Connection", "close");

	   	
}
/**
 * Function for handling the response generated by ajax call
 * @param xmlHttpRequest
 * @return
 */
function responseHandler(xmlHttpRequest)
{
	var xmlHandler=xmlHttpRequest.responseXML;
	var divCourses;
	
	if(document.getElementById("divCourses")!=null )
			divCourses=	document.getElementById("divCourses");
	
	divCourses.innerHTML="";//On next request prepare new table
	/*
	 * Storing all elements in their respective arrays
	 */
	var sCourses			=	xmlHandler.getElementsByTagName("Course");
    var sArrayCourseIds		=	xmlHandler.getElementsByTagName("CourseId");
    var sArrayCourseNames	=	xmlHandler.getElementsByTagName("CourseName");
    var sArrayExaminerIds	=	xmlHandler.getElementsByTagName("ExaminerId");
    var sArrayExaminer		=	xmlHandler.getElementsByTagName("ExaminerName");
          
    
    var sTableRows="<table id=\"tblCourses\" style=\"width:100%;\">" +
    				"<tr  style=\"background-color:#DDDDDD\;height:20px;\">" +
	    				"<th style=\"width:10%;height:10px;padding:0px 0px 0px 2px;\">S.No.</th>" +
	    				"<th style=\"width:60%;\">Course Names</th>" +
	    				"<th style=\"width:30%;\">Examiner</th>" +
    				"</tr>";
    var sNo=null,sThisRowCourseId=null,sThisRowCourseName=null,sThisExaminerId=null,sThisExaminerName=null,strStyleRow=null;

    if(sCourses.length>0)//if atleast 1 centre exists
    {
    	for(var cnt=0;cnt<sCourses.length;cnt++)
    	{
    		sNo					=	sCourses[cnt].getAttribute("id");
    		sThisRowCourseId	=	sArrayCourseIds[cnt].childNodes[0].nodeValue;
    		sThisRowCourseName	=	sArrayCourseNames[cnt].childNodes[0].nodeValue;
    		sThisExaminerId		=	sArrayExaminerIds[cnt].childNodes[0].nodeValue;
    		sThisExaminerName	=	sArrayExaminer[cnt].childNodes[0].nodeValue;
    		/*
    		 * Applying alternate styles to rows
    		 */
    		if(cnt%2==0)
    			strStyleRow="<tr class=\"even\" style=\"height:25px;\">";
    		else
    			strStyleRow="<tr class=\"odd\" style=\"height:25px;\">";
    		
    		
    		sTableRows=sTableRows+strStyleRow +
    									"<td align=\"center\" style=\"width:10%;height:15px;\" >"+sNo+".</td>" +
    									"<td align=\"left\" style=\"width:45%;height:15px;padding-left:4px;\">" +
    										"<a style=\"cursor:pointer;\" onclick=\"javascript:switchToSelectedCourse(this.id,"+sNo+")\" id="+sThisRowCourseId+">"+sThisRowCourseName+"</a>" +
    										"<input type=\"hidden\" name=\"txtExaminerId"+sNo+"\" id=\"txtExaminerId"+sNo+"\"  value="+sThisExaminerId+">"+
    									"</td>" +
    									"<td align=\"left\" style=\"width:45%;height:15px;padding-left:4px;\">"+sThisExaminerName+"</td>" +
									"</tr>";
    		
    	}
    	document.getElementById('divCourses').innerHTML=document.getElementById('divCourses').innerHTML+sTableRows+"</table>" ;
    	
    } 
    else//if no centre exists
    {
    	document.getElementById('divCourses').innerHTML="<div class=\"message_directions\" id=\"div_message_no_centres\" style=\"margin:100px 0px 0px 0px;\">" +
										    				"<br><br>No Course record found." +
										    			"</div>";
    }
    
}


/*********Ajax call for fetching centres for switch role ends***********/
function switchToSelectedCourse(courseId,sNo)
{
	var frm	=	document.getElementById('frmCourses');
	document.getElementById('txtCourseId').value=courseId;
	document.getElementById('txtExaminerUserId').value=document.getElementById("txtExaminerId".concat(sNo)).value;
	frm.submit();
}
